//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCAnswer()
        {
            this.SCAnswerDetails = new HashSet<SCAnswerDetail>();
        }
    
        public string SCEmailid { get; set; }
        public Nullable<int> Scode { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public int sno { get; set; }
        public string studytype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCAnswerDetail> SCAnswerDetails { get; set; }
        public virtual StudyType StudyType1 { get; set; }
        public virtual Study Study { get; set; }
        public virtual SCUser SCUser { get; set; }
    }
}
