//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Study()
        {
            this.SCAnswers = new HashSet<SCAnswer>();
            this.StudyQuestions = new HashSet<StudyQuestion>();
        }
    
        public int SCode { get; set; }
        public string StudyName { get; set; }
        public Nullable<int> NumStudents { get; set; }
        public string SchoolName { get; set; }
        public string StudyType { get; set; }
        public string CTEQ { get; set; }
        public string CTUQ { get; set; }
        public string CTHQ { get; set; }
        public string Other { get; set; }
        public string saemailid { get; set; }
        public string ConsentForm { get; set; }
    
        public virtual SAUser SAUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCAnswer> SCAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyQuestion> StudyQuestions { get; set; }
    }
}
