//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyEntities1 : DbContext
    {
        public SurveyEntities1()
            : base("name=SurveyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAUser> SAUsers { get; set; }
        public virtual DbSet<SCAnswerDetail> SCAnswerDetails { get; set; }
        public virtual DbSet<SCAnswer> SCAnswers { get; set; }
        public virtual DbSet<SCUser> SCUsers { get; set; }
        public virtual DbSet<Study> Studies { get; set; }
        public virtual DbSet<StudyQuestion> StudyQuestions { get; set; }
        public virtual DbSet<StudySurvey> StudySurveys { get; set; }
        public virtual DbSet<StudyType> StudyTypes { get; set; }
        public virtual DbSet<CustomSurvey> CustomSurveys { get; set; }
    }
}
